"""empty message

Revision ID: b631905b88b5
Revises: d826c705a53c
Create Date: 2026-02-02 00:32:29.892371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b631905b88b5'
down_revision = 'd826c705a53c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_bikes_bike_model_id', 'bike_models', ['bike_model_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bikes_bike_model_id', type_='foreignkey')

    # ### end Alembic commands ###
